[package]
name = "cutstudio"
version = "1.1.0"
description = "剪辑台"
authors = ["Kr1nous <https://github.com/Kr1nous>"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
